# Generated by Django 2.2 on 2021-09-20 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IPL', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matches',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
